//! GENERATED by `fz build`. The venture-linked `fz`: it sees the
//! compiled-in harness, so `fz migrations collect` etc. work here.
fn main() {
    cratefield_cli::main_for(tables_canary::harness);
}
