//! GENERATED by `fz build` from the venture manifest. Do not edit by
//! hand: re-run `fz build` to regenerate.
#![forbid(unsafe_code)]

use cratefield::cloudflare::{serve, serve_scheduled, Cloudflare};
use cratefield::Harness;
use std::sync::OnceLock;
use worker::{event, Context, Env, Request, Response};

static INSTANCE: OnceLock<(Harness, Cloudflare)> = OnceLock::new();

pub mod tables;

/// The composed venture harness (module set ``).
#[must_use]
pub fn harness() -> Harness {
    compose().0
}

/// The serving runtime for this venture.
#[must_use]
pub fn runtime() -> Cloudflare {
    Cloudflare::new().db("DB").auth_from_env()
}

fn compose() -> (Harness, Cloudflare) {
    let harness = Harness::builder()
        .venture(
            cratefield::Venture::new("tables-canary", "tables-canary.factory0.dev")
                .public_url("https://tables-canary.factory0.dev")
                .cors_origins(["https://tables-canary.factory0.dev"]),
        )
        .module(crate::tables::DeclaredTables::new())
        .runtime(runtime())
        .build()
        .expect("generated venture harness is valid");
    (harness, runtime())
}

#[event(fetch)]
/// Worker fetch entry point.
///
/// # Errors
///
/// Propagates `worker::Error` from the harness router.
pub async fn fetch(req: Request, env: Env, ctx: Context) -> worker::Result<Response> {
    let (harness, runtime) = INSTANCE.get_or_init(compose);
    serve(harness, runtime, req, env, ctx).await
}

#[event(scheduled)]
pub async fn scheduled(event: worker::ScheduledEvent, env: Env, ctx: worker::ScheduleContext) {
    let (harness, runtime) = INSTANCE.get_or_init(compose);
    serve_scheduled(harness, runtime, event, env, ctx).await;
}
