//! GENERATED by `fz build` from the venture manifest's `[tables]`
//! section. Do not edit by hand: re-run `fz build` to regenerate.
#![allow(clippy::needless_raw_string_hashes)]

use std::sync::Arc;

use cratefield::axum::Router;
use cratefield::{
    Config, ConfigError, DataKind, Disposition, Migrations, Module, ModuleContext, PersonalDataSet,
    Port, SqlMigration,
};

/// The tables this venture declares for itself.
pub struct DeclaredTables;

impl DeclaredTables {
    #[must_use]
    pub fn new() -> Self {
        Self
    }
}

impl Default for DeclaredTables {
    fn default() -> Self {
        Self::new()
    }
}

const DDL: &str = r#"-- Generated by cratefield-tables from the venture manifest.
-- Dialect: sqlite. Forward-only: this file only creates.

CREATE TABLE IF NOT EXISTS note (
    id TEXT NOT NULL,
    author TEXT NOT NULL,
    body TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tier (
    slug TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (slug)
);
"#;

const MIGRATIONS: [SqlMigration; 1] = [SqlMigration::new("0001", "tables", DDL)];

const SETS: &[PersonalDataSet] = &[
    PersonalDataSet {
        table: "note",
        subject: "author",
        kind: DataKind::Content,
        disposition: Disposition::Erase,
        description: r#"The notes you wrote, and who wrote them."#,
        redacted: &[],
        subject_via: None,
    },
    PersonalDataSet::none("tier", r#"Plan tiers; nobody is in them."#),
];

/// The declaration this module serves, as the manifest wrote it.
///
/// Text rather than emitted Rust: `TableApi` is a runtime value, and
/// this comes from a manifest `fz build` has already validated, so a
/// failure to read it is a bug in the generator rather than anything
/// an author wrote. `validate_config` reports it while the harness is
/// composing, so a deployment that cannot read its own declaration
/// refuses to start rather than serving no tables.
const DECLARED: &str = r#"{"tables":{"note":{"name":"note","primary_key":"id","fields":[{"name":"id","kind":"uuid","required":true},{"name":"author","kind":"text","required":true},{"name":"body","kind":"text","max_len":400}]},"tier":{"name":"tier","primary_key":"slug","fields":[{"name":"slug","kind":"text","required":true},{"name":"label","kind":"text","required":true}]}},"access":{"note":"owner","tier":"public-read"},"privacy":{"note":{"holds":"personal","subject":"author","kind":"content","disposition":"erase","description":"The notes you wrote, and who wrote them."},"tier":{"holds":"nothing","reason":"Plan tiers; nobody is in them."}}}"#;

impl Module for DeclaredTables {
    fn name(&self) -> &'static str {
        "tables"
    }

    fn version(&self) -> &'static str {
        env!("CARGO_PKG_VERSION")
    }

    fn requires(&self) -> &'static [Port] {
        &[Port::Db, Port::Auth]
    }

    fn tables(&self) -> &'static [&'static str] {
        &["note", "tier"]
    }

    fn personal_data(&self) -> &'static [PersonalDataSet] {
        SETS
    }

    fn migrations(&self) -> Migrations {
        const _: () = cratefield::assert_migration_set(&MIGRATIONS);
        Migrations::sqlite(&MIGRATIONS)
    }

    /// Reads the declaration, so a deployment that cannot is
    /// refused while composing rather than serving no tables.
    fn validate_config(&self, _cfg: &dyn Config) -> Result<(), ConfigError> {
        match cratefield::tables_api::parse(DECLARED) {
            Ok(_tables) => Ok(()),
            Err(why) => {
                let mut problems = ConfigError::new();
                problems.push(why);
                Err(problems)
            }
        }
    }

    fn router(&self, ctx: ModuleContext) -> Router {
        match cratefield::tables_api::parse(DECLARED) {
            Ok(tables) => {
                cratefield::tables_api::router(Arc::new(cratefield::tables_api::Tables {
                    tables,
                    ctx: Arc::new(ctx),
                }))
            }
            // Unreachable: `validate_config` ran first and the
            // composition was refused if it failed.
            Err(_unreadable) => Router::new(),
        }
    }
}
