//! DDL generation: the exact text, both dialects, and determinism.

use cratefield_tables::{Schema, SqlDialect};
use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    tables: Schema,
}

fn schema(fragment: &str) -> Schema {
    toml::from_str::<Manifest>(fragment)
        .expect("the fragment parses")
        .tables
}

/// One schema exercising every kind, every constraint, both a single and
/// a composite primary key, a foreign key and an index.
const EVERYTHING: &str = r#"
[tables.author]
primary_key = "id"

[[tables.author.fields]]
name = "id"
kind = "uuid"
required = true

[[tables.author.fields]]
name = "email"
kind = "text"
format = "email"
max_len = 254
required = true
unique = true

[tables.post]
primary_key = "id"

[[tables.post.fields]]
name = "id"
kind = "uuid"
required = true

[[tables.post.fields]]
name = "title"
kind = "text"
min_len = 1
max_len = 200
required = true

[[tables.post.fields]]
name = "status"
kind = "enum"
values = ["draft", "published"]
required = true
default = "draft"

[[tables.post.fields]]
name = "read_minutes"
kind = "integer"
default = 0

[[tables.post.fields]]
name = "score"
kind = "real"
default = 1.0

[[tables.post.fields]]
name = "featured"
kind = "boolean"
required = true
default = false

[[tables.post.fields]]
name = "body"
kind = "json"

[[tables.post.fields]]
name = "created_at"
kind = "timestamp"
required = true
indexed = true

[[tables.post.fields]]
name = "author_id"
kind = "uuid"
indexed = true

[[tables.post.foreign_keys]]
field = "author_id"
references = "author"

[tables.tag]
primary_key = ["post_id", "label"]

[[tables.tag.fields]]
name = "post_id"
kind = "uuid"

[[tables.tag.fields]]
name = "label"
kind = "text"

[[tables.tag.foreign_keys]]
field = "post_id"
references = "post"
"#;

const SQLITE_EXPECTED: &str = "\
-- Generated by cratefield-tables from the venture manifest.
-- Dialect: sqlite. Forward-only: this file only creates.

CREATE TABLE IF NOT EXISTS author (
    id TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    read_minutes INTEGER DEFAULT 0,
    score REAL DEFAULT 1.0,
    featured INTEGER NOT NULL DEFAULT 0,
    body TEXT,
    created_at TEXT NOT NULL,
    author_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);
CREATE INDEX IF NOT EXISTS post_created_at_idx ON post (created_at);
CREATE INDEX IF NOT EXISTS post_author_id_idx ON post (author_id);

CREATE TABLE IF NOT EXISTS tag (
    post_id TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (post_id, label),
    FOREIGN KEY (post_id) REFERENCES post (id)
);
";

const POSTGRES_EXPECTED: &str = "\
-- Generated by cratefield-tables from the venture manifest.
-- Dialect: postgres. Forward-only: this file only creates.

CREATE TABLE IF NOT EXISTS author (
    id TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    read_minutes BIGINT DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 1.0,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    body TEXT,
    created_at TEXT NOT NULL,
    author_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);
CREATE INDEX IF NOT EXISTS post_created_at_idx ON post (created_at);
CREATE INDEX IF NOT EXISTS post_author_id_idx ON post (author_id);

CREATE TABLE IF NOT EXISTS tag (
    post_id TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (post_id, label),
    FOREIGN KEY (post_id) REFERENCES post (id)
);
";

#[test]
fn sqlite_ddl_is_exactly_this() {
    let sql = schema(EVERYTHING).ddl(SqlDialect::Sqlite).expect("renders");
    assert_eq!(sql, SQLITE_EXPECTED);
}

#[test]
fn postgres_ddl_is_exactly_this() {
    let sql = schema(EVERYTHING)
        .ddl(SqlDialect::Postgres)
        .expect("renders");
    assert_eq!(sql, POSTGRES_EXPECTED);
}

#[test]
fn the_same_definition_always_renders_byte_identical_sql() {
    // Twice from one value, and once more from a second parse of the same
    // manifest, which is what would catch an iteration order that depends
    // on a hash map rather than on the declaration.
    for dialect in SqlDialect::ALL.iter().copied() {
        let once = schema(EVERYTHING).ddl(dialect).expect("renders");
        let twice = schema(EVERYTHING).ddl(dialect).expect("renders");
        let reparsed = schema(EVERYTHING).ddl(dialect).expect("renders");
        assert_eq!(once.as_bytes(), twice.as_bytes());
        assert_eq!(once.as_bytes(), reparsed.as_bytes());
    }
}

#[test]
fn the_manifests_section_order_does_not_reach_the_sql() {
    let declared = schema(EVERYTHING);
    let mut shuffled = declared.clone();
    shuffled.tables.reverse();
    // `Schema::new` is what a caller uses to build a schema by hand, and
    // it sorts, so a reversed input renders the same script.
    let sorted = Schema::new(shuffled.tables);
    assert_eq!(
        sorted.ddl(SqlDialect::Sqlite).expect("renders"),
        declared.ddl(SqlDialect::Sqlite).expect("renders")
    );
}

#[test]
fn both_dialects_pass_the_portable_sql_lint() {
    // The same predicate `fz doctor` runs over a module's migrations and
    // the Postgres runner uses to pick a migration set.
    for dialect in SqlDialect::ALL.iter().copied() {
        let sql = schema(EVERYTHING).ddl(dialect).expect("renders");
        let hits = cratefield_core::lint_portable_sql(&sql);
        assert!(hits.is_empty(), "{}: {hits:?}", dialect.name());
    }
}

#[test]
fn generated_ddl_only_creates() {
    for dialect in SqlDialect::ALL.iter().copied() {
        let sql = schema(EVERYTHING)
            .ddl(dialect)
            .expect("renders")
            .to_uppercase();
        assert!(!sql.contains("DROP "), "forward-only: no DROP");
        assert!(!sql.contains("ALTER "), "forward-only: no ALTER");
        assert!(!sql.contains("DELETE "), "forward-only: no DELETE");
    }
}

#[test]
fn an_invalid_definition_renders_no_sql() {
    let schema = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
[[tables.post.fields]]
name = "order"
kind = "text"
"#,
    );
    let error = schema
        .ddl(SqlDialect::Sqlite)
        .expect_err("a reserved word must not reach SQL");
    assert!(
        error.problems.iter().any(|line| line.contains("reserved")),
        "{:#?}",
        error.problems
    );
}

#[test]
fn a_quote_in_a_literal_is_doubled() {
    let sql = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
[[tables.post.fields]]
name = "note"
kind = "text"
default = "it's here"
[[tables.post.fields]]
name = "state"
kind = "enum"
values = ["it's on", "off"]
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert!(sql.contains("DEFAULT 'it''s here'"), "{sql}");
    assert!(sql.contains("IN ('it''s on', 'off')"), "{sql}");
}

#[test]
fn a_unique_or_primary_key_field_gets_no_second_index() {
    let sql = schema(
        r#"
[tables.post]
primary_key = "id"
[[tables.post.fields]]
name = "id"
kind = "uuid"
indexed = true
[[tables.post.fields]]
name = "slug"
kind = "text"
unique = true
indexed = true
[[tables.post.fields]]
name = "author_id"
kind = "uuid"
indexed = true
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert_eq!(sql.matches("CREATE INDEX").count(), 1, "{sql}");
    assert!(sql.contains("post_author_id_idx"), "{sql}");
}

#[test]
fn an_index_name_longer_than_an_identifier_is_rejected() {
    let long = "a".repeat(60);
    let fragment = format!(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
[[tables.post.fields]]
name = "{long}"
kind = "text"
indexed = true
"#
    );
    let error = schema(&fragment)
        .ddl(SqlDialect::Sqlite)
        .expect_err("post_<60 chars>_idx is 69 characters");
    assert!(
        error
            .problems
            .iter()
            .any(|line| line.contains("generated index name")),
        "{:#?}",
        error.problems
    );
}

#[test]
fn an_integral_default_written_as_a_decimal_renders_as_an_integer() {
    let sql = schema(
        r#"
[tables.post]
[[tables.post.fields]]
name = "id"
kind = "uuid"
[[tables.post.fields]]
name = "views"
kind = "integer"
default = 42.0
"#,
    )
    .ddl(SqlDialect::Sqlite)
    .expect("renders");
    assert!(sql.contains("views INTEGER DEFAULT 42"), "{sql}");
}
