//! Generating the module that carries a venture's declared tables
//! (issue #153).
//!
//! `[tables]` is a declaration, and a declaration has to become something
//! the harness composes or it is a section that does nothing. This writes
//! that something: one module, in the generated venture's own source,
//! whose `migrations()` is the rendered DDL and whose `personal_data()`
//! is what the author declared.
//!
//! # Why generated source rather than a runtime module
//!
//! `PersonalDataSet` is `&'static str` all the way down — deliberately,
//! because the declarations it holds are compiled in and a module cannot
//! assemble one from a config value it read. A venture's tables are
//! declared in a manifest, which is runtime data, so the only way to get
//! from one to the other is to generate source. That is what `fz build`
//! already does, so the tables module is emitted the same way the rest of
//! the venture is.
//!
//! # No routes
//!
//! `router()` is empty. Serving the declared tables is the CRUD layer,
//! which is not built; the module exists so the tables are *created*,
//! declared to `fz data export`, and reachable by subject access and
//! erasure. A module that created tables nobody had declared would be the
//! hole #272 was about, the other way round.

use std::fmt::Write as _;

use cratefield_tables::{Schema, SqlDialect};

use crate::manifest::VentureManifest;
use crate::privacy::{Disposition, TablePrivacy};

/// The module's name, and so its route prefix if it ever grows one.
pub(crate) const MODULE_NAME: &str = "tables";

/// The file the generator writes.
pub(crate) const PATH: &str = "src/tables.rs";

/// The Rust type the composition names.
pub(crate) const TYPE: &str = "DeclaredTables";

/// Renders `src/tables.rs` for a manifest that declares tables.
///
/// The caller checks `manifest.tables` is non-empty; this renders what it
/// is given.
pub(crate) fn tables_rs(manifest: &VentureManifest) -> String {
    let mut out = String::new();
    out.push_str(
        "//! GENERATED by `fz build` from the venture manifest's [tables]\n\
         //! section. Do not edit by hand: re-run `fz build` to regenerate.\n\
         #![allow(clippy::needless_raw_string_hashes)]\n\n\
         use std::sync::Arc;\n\n\
         use cratefield::axum::Router;\n\
         use cratefield::{\n\
         \x20   Config, ConfigError, DataKind, Disposition, Migrations, Module, ModuleContext,\n\
         \x20   PersonalDataSet, Port, SqlMigration,\n\
         };\n\n",
    );

    let _ = write!(
        out,
        "/// The tables this venture declares for itself.\n\
         pub struct {TYPE};\n\n\
         impl {TYPE} {{\n\
         \x20   #[must_use]\n\
         \x20   pub fn new() -> Self {{\n\
         \x20       Self\n\
         \x20   }}\n\
         }}\n\n\
         impl Default for {TYPE} {{\n\
         \x20   fn default() -> Self {{\n\
         \x20       Self::new()\n\
         \x20   }}\n\
         }}\n\n"
    );

    // The DDL, as one migration. One rather than one per table because
    // the renderer already orders them so a referenced table is created
    // before the table referencing it, and splitting would put that
    // ordering in the file names instead.
    let ddl = manifest
        .tables
        .ddl(SqlDialect::Sqlite)
        .unwrap_or_else(|_| String::new());

    let _ = write!(
        out,
        "const DDL: &str = r#\"{ddl}\"#;\n\n\
         const MIGRATIONS: [SqlMigration; 1] = [SqlMigration::new(\"0001\", \"tables\", DDL)];\n\n"
    );

    out.push_str(&personal_data_const(manifest));

    let _ = write!(
        out,
        "/// The declaration this module serves, as the manifest wrote it.\n\
         ///\n\
         /// Text rather than emitted Rust: `TableApi` is a runtime value, and\n\
         /// this comes from a manifest `fz build` has already validated, so a\n\
         /// failure to read it is a bug in the generator rather than anything\n\
         /// an author wrote. `validate_config` reports it while the harness is\n\
         /// composing, so a deployment that cannot read its own declaration\n\
         /// refuses to start rather than serving no tables.\n\
         const DECLARED: &str = {declared};\n\n",
        declared = quoted(&declared_json(manifest))
    );

    out.push_str(&module_impl(manifest));
    out
}

/// The `impl Module` block: what the module is called, what it needs, and
/// the router that serves what it declares.
///
/// Its own function because `tables_rs` is at clippy's line limit and
/// this is the part that grew — the module went from creating tables to
/// serving them.
fn module_impl(manifest: &VentureManifest) -> String {
    let mut out = String::new();
    let names = manifest
        .tables
        .tables
        .iter()
        .map(|table| format!("\"{}\"", table.name))
        .collect::<Vec<_>>()
        .join(", ");
    let ports = required_ports(manifest);

    let _ = write!(
        out,
        "impl Module for {TYPE} {{\n\
         \x20   fn name(&self) -> &'static str {{\n\
         \x20       \"{MODULE_NAME}\"\n\
         \x20   }}\n\n\
         \x20   fn version(&self) -> &'static str {{\n\
         \x20       env!(\"CARGO_PKG_VERSION\")\n\
         \x20   }}\n\n\
         \x20   fn requires(&self) -> &'static [Port] {{\n\
         \x20       {ports}\n\
         \x20   }}\n\n\
         \x20   fn tables(&self) -> &'static [&'static str] {{\n\
         \x20       &[{names}]\n\
         \x20   }}\n\n\
         \x20   fn personal_data(&self) -> &'static [PersonalDataSet] {{\n\
         \x20       SETS\n\
         \x20   }}\n\n\
         \x20   fn migrations(&self) -> Migrations {{\n\
         \x20       const _: () = cratefield::assert_migration_set(&MIGRATIONS);\n\
         \x20       Migrations::sqlite(&MIGRATIONS)\n\
         \x20   }}\n\n\
         \x20   /// Reads the declaration, so a deployment that cannot is\n\
         \x20   /// refused while composing rather than serving no tables.\n\
         \x20   fn validate_config(&self, _cfg: &dyn Config) -> Result<(), ConfigError> {{\n\
         \x20       match cratefield::tables_api::parse(DECLARED) {{\n\
         \x20           Ok(_tables) => Ok(()),\n\
         \x20           Err(why) => {{\n\
         \x20               let mut problems = ConfigError::new();\n\
         \x20               problems.push(why);\n\
         \x20               Err(problems)\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\n\
         \x20   fn router(&self, ctx: ModuleContext) -> Router {{\n\
         \x20       match cratefield::tables_api::parse(DECLARED) {{\n\
         \x20           Ok(tables) => cratefield::tables_api::router(Arc::new(\n\
         \x20               cratefield::tables_api::Tables {{\n\
         \x20                   tables,\n\
         \x20                   ctx: Arc::new(ctx),\n\
         \x20               }},\n\
         \x20           )),\n\
         \x20           // Unreachable: `validate_config` ran first and the\n\
         \x20           // composition was refused if it failed.\n\
         \x20           Err(_unreadable) => Router::new(),\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n"
    );
    out
}

/// The declaration the generated module carries, as JSON.
///
/// The three parts `cratefield_tables_api::Declared` reads: the tables,
/// who may reach each, and what each holds — the last for the subject
/// column, which is what `owner` matches a caller against.
/// Rendered through [`quoted`] rather than a bare `r#"..."#`: a
/// description containing `\"#` puts that sequence in the JSON, and a
/// one-hash raw literal ends there. The same trap `quoted` exists for.
fn declared_json(manifest: &VentureManifest) -> String {
    serde_json::json!({
        "tables": manifest.tables,
        "access": manifest.table_access,
        "privacy": manifest.table_privacy,
    })
    .to_string()
}

/// The ports the generated module declares.
///
/// `Port::Db` always — the module's whole job is creating the tables.
/// `Port::Auth` as soon as one declared table's access level is anything
/// but `public-read`, because every other level is a question about who
/// is asking and the harness answers it through that port.
///
/// Declared rather than looked up at request time, which is the point. A
/// module whose required port the runtime does not provide is a build
/// error (`Harness::build`), so a venture with an `owner` table and no
/// verifier wired **refuses to start**. Without this the deployment would
/// boot, serve every other route, and only fail when somebody read that
/// table — which is the same outage discovered later and by a user.
///
/// A level this build does not recognise counts as needing a verifier:
/// `public-read` is the only one that does not, so anything else is
/// treated as something, and the safe guess is that it asks who you are.
fn required_ports(manifest: &VentureManifest) -> &'static str {
    let needs_a_caller = manifest
        .table_access
        .values()
        .any(|access| *access != crate::access::Access::PublicRead);
    if needs_a_caller {
        "&[Port::Db, Port::Auth]"
    } else {
        "&[Port::Db]"
    }
}

/// The `personal_data()` table, rendered from what the author declared.
///
/// Every declared table has an entry, because the manifest refuses one
/// that does not (see [`crate::privacy`]) — so this cannot silently emit
/// a shorter list than `tables()` names.
fn personal_data_const(manifest: &VentureManifest) -> String {
    let mut out = String::new();
    out.push_str("const SETS: &[PersonalDataSet] = &[\n");
    for table in &manifest.tables.tables {
        let Some(declaration) = manifest.table_privacy.get(&table.name) else {
            continue;
        };
        match declaration {
            TablePrivacy::Nothing { reason } => {
                let _ = writeln!(
                    out,
                    "    PersonalDataSet::none(\"{name}\", {reason}),",
                    name = table.name,
                    reason = quoted(reason)
                );
            }
            TablePrivacy::Personal {
                subject,
                kind,
                disposition,
                description,
                redacted,
            } => {
                let _ = write!(
                    out,
                    "    PersonalDataSet {{\n\
                     \x20       table: \"{name}\",\n\
                     \x20       subject: \"{subject}\",\n\
                     \x20       kind: DataKind::{kind},\n\
                     \x20       disposition: {disposition},\n\
                     \x20       description: {description},\n\
                     \x20       redacted: &[{redacted}],\n\
                     \x20       subject_via: None,\n\
                     \x20   }},\n",
                    name = table.name,
                    kind = camel(kind),
                    disposition = rendered_disposition(disposition),
                    description = quoted(description),
                    redacted = redacted
                        .iter()
                        .map(|column| format!("\"{column}\""))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
            }
        }
    }
    out.push_str("];\n\n");
    out
}

fn rendered_disposition(disposition: &Disposition) -> String {
    match disposition {
        Disposition::Erase => "Disposition::Erase".to_owned(),
        Disposition::Retain(reason) => format!("Disposition::Retain({})", quoted(reason)),
        Disposition::Anonymise(columns) => format!(
            "Disposition::Anonymise(&[{}])",
            columns
                .iter()
                .map(|column| format!("\"{column}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// `contact` -> `Contact`. The wire names are single words, which is why
/// this is a capitalisation rather than a snake-to-camel conversion.
fn camel(kind: &str) -> String {
    let mut chars = kind.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_uppercase().collect::<String>() + chars.as_str()
    })
}

/// A Rust string literal for author-supplied prose.
///
/// A raw literal with a hash count that the text cannot close: the
/// descriptions are written by a person and go into generated source, so
/// a quote or a backslash in one must not be able to end the literal or
/// start an escape. Counting the hashes is what makes that true for any
/// text rather than for the text tried so far.
fn quoted(text: &str) -> String {
    let mut hashes = 1;
    while text.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{text}\"{fence}")
}

/// Whether a manifest has tables to generate a module for.
pub(crate) fn declares_tables(manifest: &VentureManifest) -> bool {
    !Schema::is_empty(&manifest.tables)
}
